;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-newline
        backward-sentence
        backward-sexp
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        dabbrev-expand
        delete-horizontal-space
        delete-indentation
        downcase-region
        end-of-buffer
        end-of-visual-line
        fill-paragraph
        forward-sexp
        indent-for-tab-command
        insert-register
        kill-region
        paredit-backward-up
        paredit-forward
        paredit-forward-delete
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        compile
        counsel-M-x
        kmacro-end-macro
        scroll-other-window
        ))
