;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-newline
        backward-sexp
        c-electric-brace
        c-electric-delete-forward
        c-electric-paren
        delete-horizontal-space
        delete-indentation
        downcase-region
        end-of-visual-line
        forward-sexp
        indent-for-tab-command
        kill-region
        paredit-backward-up
        paredit-forward
        paredit-forward-delete
        paredit-open-round
        ))

(setq mc/cmds-to-run-once
      '(
        compile
        counsel-M-x
        ))
