(require 'cc-mode)
(require 'clang-format)
(require 'cmake-ide)
(require 'cmake-mode)

(setq-default c-basic-offset 4)
(setq-default indent-tabs-mode nil)
(setq c-default-style '((awk-mode . "awk")
			(other . "java")))
(c-set-offset 'innamespace 0)
(c-set-offset 'label (vector 0))
(c-set-offset 'inextern-lang 0)
(c-set-offset 'topmost-intro-cont 0)
(setq-default c-offsets-alist c-offsets-alist)
;; (require 'rtags)
(cmake-ide-setup)
