(require 'ivy)
(require 'swiper)
(require 'counsel)

(ivy-mode 1)
(global-set-key (kbd "C-s") #'swiper)
(global-set-key (kbd "C-c C-r") #'ivy-resume)
(global-set-key (kbd "M-x") #'counsel-M-x)
(global-set-key (kbd "C-x C-f") #'counsel-find-file)
(global-set-key (kbd "<f1> f") #'counsel-describe-function)
(global-set-key (kbd "<f1> v") #'counsel-describe-variable)
(global-set-key (kbd "<f1> l") #'counsel-find-library)
(global-set-key (kbd "<f1> i") #'counsel-info-lookup-symbol)
(global-set-key (kbd "<f1> u") #'counsel-unicode-char)
(global-set-key (kbd "C-c s") #'counsel-ag)
(define-key read-expression-map (kbd "C-r") #'counsel-expression-history)
